import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "../components/ui/sidebar"
import "./globals.css";
import { AppSidebar } from "./_components/AppSidebar";
import { ClerkProvider } from '@clerk/nextjs'
import Provider from './Provider'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Axenra",
  description: "Generated by Prashant",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link
            href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
            rel="stylesheet"
          />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SidebarProvider>
            <AppSidebar />
            <SidebarTrigger />
            <Provider>
              {children}
            </Provider>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
